# 每轮问答间隔的时间，单位秒，默认300（5分钟）
interval: 300

# 每轮问答持续的最大时间，单位秒，默认30
duration: 30

# 玩家回答错误时是否给予单独提示回答错误，默认false
notify-wrong-answer: false

# 参与问答的最少在线人数，如果人数不足则暂停问答
min-player: 5

# 当人数满足或不满足 min-player 条件时，是否广播状态变更消息
broadcast-status: true

# 是否显示倒计时 BossBar
show-bossbar: true

# 玩家回答正确后，是否隐藏该条聊天消息（默认 false，即不隐藏，全服都能看到该玩家回答了正确答案）
# 如果设为 true，则该玩家的消息会被拦截，只有插件发的“xxx回答正确”提示
hide-correct: false

# 隐藏判断题时玩家回答的答案（仅隐藏 ansYes 和 ansNo 配置内容）
hide-judge-answer: true

# 是否禁用所有声音提示
mute: false

judge:
  ansYes: "是"
  ansNo: "否"

fill:
  - quiz: "这道题仅回答A才为正确答案"
    answer:
      type: text
      value: [ "A" ]
  - quiz: "这道题回答A或B为正确答案"
    answer:
      type: text
      value: [ "A", "B" ]
  - quiz: "这是一道判断题，回答配置中的ansYes内容即判为正确"
    answer:
      type: judge
      value: true

math:
  chance: 0.5 # 每轮问题为数学运算题的概率
  operator: # 运算符出现的数量
    min: 1
    max: 3
  number: # 运算数字允许的范围
    min: 1
    max: 50
  easy-multiplier:
    enable: true
    min: 2
    max: 9

prize:
  item:
    enable: true
    # ItemStack的base64编码形式
    base64: ""
    # 若 base64 不为空则优先使用 base64，否则使用 id 构建基础物品
    id: "minecraft:diamond"
    amount:
      min: 1
      max: 3
  economy: # 经济奖励
    enable: true
    amount:
      min: 10
      max: 50